### PR TITLE
Update to MathOptInterface

### PR DESCRIPTION
**Pull request by BrendonChau**
I've updated the source code, documentation, and tests to using MathOptInterface from MathProgBase. Something that was a little tricky was initializing SLSQP as the default option in NLopt when no solver is provided, but I believe my workaround should be safe to use.

### CODE REVIEW

**Comment by Hua-Zhou** [comment]
@kos-y please review, merge, and bump the version. Also need to update the OrdinalGWAS.jl package.

**Comment by kose-y** [comment]
Thank you, Brendon. Looks good to me. It will be merged after some more testing.

**Comment by kose-y** [comment]
@BrendonChau Brendon, would you please check if this new implementation is doing the identical thing as the previous version at the lower level? It got about 1.5x slower in one test, and is taking forever in another in the test of OrdinalGWAS.jl.

**Comment by BrendonChau** [comment]
I double checked, and I didn't see any difference in timing between using MathProgBase and MathOptInterface. I checked the newest commit you made for OrdinalGWAS and think this might be the problem:

```
const default_solver = NLopt.Optimizer()
MOI.set(default_solver, 
    MOI.RawOptimizerAttribute("algorithm"), :LD_SLSQP)
MOI.set(default_solver, 
    MOI.RawOptimizerAttribute("max_iter"), 4000)
```

This will allocate a single instance of an `NLopt.Optimizer` object and reuse it every time `default_solver` is passed as an argument. I double checked this by looking at the pointer for `default_solver` and looking at the field `default_solver.variable_info`. This will keep adding variables to the solver instance each time `polr()` is called. I think a safer way to avoid this is to explicitly construct a solver instance when each call is made.

**Comment by kose-y** [comment]
Thanks for the tip. I'm pretty new to MathOptInterface... However, the tests are still hanging with creating a separate instance of `NLopt.Optimizer` each time.

**Pull request merged**
